config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :dogs
  resources :users

  get 'dogs/like/:id' => 'dogs#like'
  #get ':dogs/:like/:id'
  #get dogs#like
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
  has_many_attached :images
  has_and_belongs_to_many :users
  has_many :likes

  #being handled by _form.html.erb
  def add_owner u
    p "add owner #{u.name}"
    self.users << u
  end


  def number_of_likes_per_hour
    self.likes.where("created_at > ?", 1.hour.ago).count
  end


end

app/models/dog_user.rb
class DogUser < ApplicationRecord
  self.tablename = "dogs_users"
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :dog
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :dog
end

app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :dogs
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :trackable, :validatable
  #has_one :dog
  #has_and_belongs_to_many :dogs
  def self.current_user
    User.find_by_name(:Scott)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [ :show, :edit, :update, :destroy, :like]

  # GET /dogs
  # GET /dogs.json
  def index
    @dogs = Dog.all
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    #@d= nil
    id = Dog.all.collect{|d| d.id}.sample
    if !id.nil?
      @d = Dog.find(id) if !id.nil?
    else
      @d= nil
    end

    @dog = Dog.new
    @users = User.all.order(:name)
  end

  # GET /dogs/1/edit
  def edit
    # p '____in edit___'
    # @dog = Dog.find(1)
    @users = User.all#.order(:name)
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        @dog.images.attach(params[:dog][:image]) if params[:dog][:image].present?

        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|

      if @dog.update(dog_params)
        if !params[:users].blank?
          @dog.users << User.find(params[:users])
        end

        @dog.images.attach(params[:dog][:image]) if params[:dog][:image].present?
        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like
    p 'dog likes'
    @dog.likes << Like.new
    redirect_to @dog
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.require(:dog).permit(:name, :description, :images, :users)
    end
end

app/controllers/owners_controller.rb
# not used

class OwnersController < ApplicationController
before_action :set_owner, only: [:show, :edit, :update, :destroy]

  def index
    @dog = Dog.first  #temp assn - need to be passed in
    @users = User.all
  end

  # select user u
  # @dog.users << u

  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @dog = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.require(:dog).permit(:name, :description, :images)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dogs/_form.html.erb
<%= simple_form_for @dog do |f| %>
  <%= f.input :name %>
  <%= f.input :description, as: :text %>
  <%= f.input :image, as: :file %>
  <%=select_tag :users, options_from_collection_for_select(@users, "id", "name"), include_blank: true  %>

  <% if @dog.images.any? %>
    <%= image_tag @dog.images.first %>
  <% end %>

  <%= f.button :submit %>
<% end %>

app/views/dogs/_thumbnail.html.erb
<a href="<%= url_for(dog) %>">
  <article>
    <h2 class="dog-name"><%= dog.name %></h2>
    <%= image_tag url_for(dog.images.first), class: "dog-photo", alt: "Photo of #{dog.name}" %>
  </article>
</a>

app/views/dogs/edit.html.erb
<h1>Edit Your Dog</h1>
<%= render partial: 'form' %>

app/views/dogs/index.html.erb
<%= render partial: 'thumbnail', collection: @dogs, as: :dog %>

app/views/dogs/new.html.erb
<h1>Add Your Dog</h1>
<%= render partial: 'form' %>

<% if !@d.nil? %>
  <% @d.images.each do |image| %>
    <%= image_tag url_for(image), alt: "Photo of #{@dog.name}" %>
  <% end %>
<% end %>

app/views/dogs/show.html.erb
<section>
  <h2><%= @dog.name %></h2>

  <% @dog.images.each do |image| %>
    <%= image_tag url_for(image), alt: "Photo of #{@dog.name}" %>
  <% end %>

  <p><%= @dog.description %></p>


  <%if @dog.users.include?(User.current_user) %>
    <%= link_to "Edit #{@dog.name}'s Profile", edit_dog_path %>
    <br>
    <%= link_to "Delete #{@dog.name}'s Profile", dog_path, method: :delete, data: { confirm: 'Are you sure?' } %>
    <br>
    <%= link_to "Associate User"%>
  <% else %>
    <%= link_to "Like", controller: "dogs", action: "like"%>
  <% end %>

  Current Owners(s)
  <% @dog.users.each do |user| %>
    <%= user.name %>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BarkboxChallenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>